//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_COM_WEB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empregados
    {
        public int EmpregadoID { get; set; }
        public string Nome { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> Idade { get; set; }
        public Nullable<decimal> Salario { get; set; }
    }
}
